version: '2.1'

services:
  client:
    image: localhost:5000/hadoop-pash-base:$RELEASE
    networks:
      - hbase
    volumes:
      - ${PWD}/dspash-config.json:${DISH_TOP}/pash/cluster.json
      - ${PWD}/base/run.sh:/run.sh
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    command: "/run.sh"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
networks:
  hbase:
    name: hbase
    external: true
